perf README.md & data init all in test
OJ-lab/oj-lab-platform pull request #41
Opened 2024-03-08 11:47 UTC by Zztrans

We used `mirage_db` to init PG data and `test` to init minio data before, which seem to be not consistent.

Currently, all use `go test`.

Also perf the README.md.

2024-03-08 12:33 UTC, KanadeSiina commented on tests/core/pg_test.go
> +}
Maybe we should make the test idempotent, and use an additional script to import problem package.

2024-03-08 12:34 UTC, KanadeSiina requested changes
See my comment, an additional script is preferred.

2024-03-08 17:36 UTC, Zztrans commented
> See my comment, an additional script is preferred.

script `read_pkg` has been added.

2024-03-09 01:38 UTC, slhmy requested changes
Almost good enough ~

2024-03-09 01:38 UTC, slhmy commented on tests/core/minio_test.go
>  }
Simply remove these code will be find

2024-03-09 01:38 UTC, slhmy commented on tests/mapper/user_test.go
> +		// Roles:    []*model.Role{{Name: ""}}, // If added, foreign key constraint make it can't be delete.
We should fix this, actually I remember there's something similiar with this problem in `problem` mapper.

2024-03-09 01:38 UTC, slhmy commented on src/application/init_db/main.go
> +	// })
Remove these code will be fine.

2024-03-13 14:10 UTC, slhmy approved these changes

2024-03-13 14:13 UTC, slhmy commented
Still has something need to perf (like we don't leave dead code too often)

But I don't want to hang too long on this PR, so merging it.

2024-03-13 14:16 UTC, merged